/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_administrator_ndk_crypto_Crypto */

#ifndef _Included_com_example_administrator_ndk_crypto_Crypto
#define _Included_com_example_administrator_ndk_crypto_Crypto
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_administrator_ndk_crypto_Crypto
 * Method:    encrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_administrator_ndk_1crypto_Crypto_encrypt
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_administrator_ndk_crypto_Crypto
 * Method:    decrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_administrator_ndk_1crypto_Crypto_decrypt
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
